language: python
python:
  - "2.7"
  - "3.5"

services:
  - docker

addons:
  apt:
    packages:
    - graphviz

before_install:
  - make up

script:
  - sleep 20
  - sed -i 's/kernelspec//' docs.ipynb
  - make test
